Feature/login02
URECA-TEAM3/moongchee-client pull request #10
Opened 2024-10-25 06:42 UTC by Eu1j1n

2024-10-26 04:00 UTC, skang9810 requested changes

2024-10-26 04:00 UTC, skang9810 commented on src/assets/images/doggum.svg
이거 이미 assets/icons 에 있어!

2024-10-26 04:00 UTC, skang9810 commented on package.json
리덕스 지웁시당

2024-10-26 04:00 UTC, skang9810 commented on src/pages/main/ChargePage.jsx
이거 pages/mypage 로 옮기면 좋을듯

2024-10-26 04:02 UTC, skang9810 requested changes

2024-10-26 04:02 UTC, skang9810 commented on src/pages/main/LoginPage.jsx
이거 이미 develop에서 내가 고쳐놔서 다 빼도 돼!

2024-10-28 04:29 UTC, yewoniiii approved these changes

2024-10-29 00:36 UTC, skang9810 requested changes

2024-10-29 00:36 UTC, skang9810 commented on package.json
> -    "react-icons": "^5.3.0",
다시 컴백 플리즈

2024-10-29 00:36 UTC, skang9810 commented on src/store.js
없애기

2024-10-29 00:55 UTC, skang9810 approved these changes

2024-10-29 04:23 UTC, merged