Feature/mypage
URECA-TEAM3/moongchee-client pull request #13
Opened 2024-10-29 08:18 UTC by yewoniiii

2024-10-29 10:15 UTC, skang9810 requested changes

2024-10-29 10:15 UTC, skang9810 commented on src/pages/mypage/Mypage.jsx
> +          <button onClick={handleEditUserInfoClick} className='border-2 border-blue-500 text-primary text-sm rounded-xl w-16 h-7'>편집</button>
변경사항:
- border-2 --> border
- border-blue-500 --> border-primary
- rounded-xl --> rounded-lg

추가:
- hover:bg-primary
- hover:text-white

2024-10-29 10:15 UTC, skang9810 commented on src/pages/mypage/Mypage.jsx
> +              <img src='/src/assets/images/dogChew.svg' className="w-12 h-12 rounded-full" />
DogChew 라는 컴포넌트가 이미 있어서 그거 그대로 사용하면 될거야!

2024-10-29 10:15 UTC, skang9810 commented on src/pages/mypage/Mypage.jsx
> +                <h2 className='text-lg font-extrabold mb-6'>로그아웃 하시겠습니까?</h2>
font-extrabold --> font-bold

2024-10-29 10:15 UTC, skang9810 commented on src/pages/mypage/ShopHistory.jsx
> +                        <ChevronLeftIcon className="h-6 w-6 ml-5" stroke="black" />
이거 방향이 위아래가 반대로 되어있어. 닫혀있을때에는 아래를 향하도록 해야 할 것 같엉

2024-10-29 10:15 UTC, skang9810 commented on src/pages/mypage/ShopHistory.jsx
> +                                    <img src='/src/assets/images/dogChew.svg' className='w-6 h-6 rounded-full' />
이 파일에 있는 개껌 아이콘도 컴포넌트로 대체하기!

2024-10-30 01:30 UTC, skang9810 approved these changes

2024-10-30 01:41 UTC, jugpark approved these changes

2024-10-30 01:41 UTC, merged